language: cpp
dist: trusty
sudo: required
before_install:
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get -qq update
  - sudo apt-get install -q -y gcc-5 g++-5
  - export CC=gcc-5 CXX=g++-5
  - >
    sudo apt-get install -q -y \
      libsdl2-dev \
      libsdl2-image-dev \
      libsdl2-net-dev \
      libsdl2-mixer-dev \
      libglew-dev \
      libfreetype6-dev \
      libreadline-dev
script: mkdir build && cd build && cmake ../src && make -j 2 && ./ta3d/src/ta3d_test
